import {
    Loader2,
    Moon,
    SunMedium,
    Twitter,
    Check,
    ChevronLeft,
    ChevronRight,
    Command,
    CreditCard,
    File,
    FileText,
    Github,
    Laptop,
    LifeBuoy,
    LogOut,
    Star,
    Mail,
    MessageSquare,
    Plus,
    Minus,
    PlusCircle,
    Settings,
    Trash2,
    User,
    UserPlus,
    Users,
    X,
    ToggleLeft as Google,
    Image,
    MoreVertical,
    AlertTriangle,
    ArrowRight,
    ArrowUp,
    Facebook,
    Apple,
    Search,
    Phone,
    ShoppingCart,
    Bell,
    Menu,
    Heart,
    RefreshCw,
    Eye,
    EyeOff,
    Info,
    QrCode,
    Smartphone,
    Clock,
    CheckCircle,
    XCircle,
    AlertCircle,
    Coins as Token,
    Grid,
    List,
    TrendingUp,
    Wallet,
    Package,
    Edit,
    MapPin,
    ArrowLeft,
    Truck,
    ShoppingBag,
    History,
    Download,
    Store,
    Gamepad,
    Play,
    Save,
    Camera,
    Monitor,
    Watch,
    Tablet,
    ChevronDown,
    Tag,
    Filter,
    Sliders,
    Home,
    Briefcase,
    Building,
    Shield,
    Ticket,
    Headphones as Headset,
    RefreshCcw,
    PiggyBank,
    Lock,
    Sparkles,
    Instagram,
    Trophy,
    Award,
    PenTool,
    LogIn,
    ThumbsUp,
    Repeat,
    Zap as Zap,
    Megaphone
  
  } from "lucide-react";
  
  export const Icons = {
    logo: Command,
    close: X,
    spinner: Loader2,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronDown: ChevronDown,
    trash: Trash2,
    post: FileText,
    page: File,
    media: Image,
    settings: Settings,
    creditCard: CreditCard,
    ellipsis: MoreVertical,
    add: Plus,
    minus: Minus,
    warning: AlertTriangle,
    user: User,
    arrowRight: ArrowRight,
    arrowLeft: ArrowLeft,
    arrowUp: ArrowUp,
    help: LifeBuoy,
    twitter: Twitter,
    check: Check,
    google: Google,
    gitHub: Github,
    facebook: Facebook,
    apple: Apple,
    instagram: Instagram,
    sun: SunMedium,
    moon: Moon,
    search: Search,
    phone: Phone,
    shoppingCart: ShoppingCart,
    bell: Bell,
    menu: Menu,
    heart: Heart,
    refreshCw: RefreshCw,
    refresh: RefreshCcw,
    eye: Eye,
    eyeOff: EyeOff,
    info: Info,
    qrCode: QrCode,
    smartphone: Smartphone,
    clock: Clock,
    checkCircle: CheckCircle,
    xCircle: XCircle,
    alertCircle: AlertCircle,
    token: Token,
    plus: Plus,
    star: Star,
    grid: Grid,
    list: List,
    trendingUp: TrendingUp,
    wallet: Wallet,
    userPlus: UserPlus,
    package: Package,
    logout: LogOut,
    edit: Edit,
    mapPin: MapPin,
    users: Users,
    truck: Truck,
    x: X,
    shoppingBag: ShoppingBag,
    history: History,
    download: Download,
    store: Store,
    image: Image,
    gamepad: Gamepad,
    play: Play,
    save: Save,
    camera: Camera,
    monitor: Monitor,
    watch: Watch,
    tablet: Tablet,
    laptop: Laptop,
    tag: Tag,
    filter: Filter,
    sliders: Sliders,
    home: Home,
    briefcase: Briefcase,
    building: Building,
    mail: Mail,
    shield: Shield,
    ticket: Ticket,
    headset: Headset,
    piggyBank: PiggyBank,
    lock: Lock,
    sparkles: Sparkles,
    alertTriangle: AlertTriangle,
    trophy: Trophy,
    award: Award,
    fileText: FileText,
    penTool: PenTool,
    logIn: LogIn,
    thumbsUp: ThumbsUp,
    repeat: Repeat,
    refreshCcw: RefreshCcw,
    zap: Zap,
    megaphone: Megaphone,
  } as const;